table dim_date
	dataCategory: Time

	column date
		dataType: dateTime
		formatString: Long Date
		isKey
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: string
		summarizeBy: none
		sourceColumn: month

	column iso_week
		dataType: int64
		summarizeBy: none
		sourceColumn: iso_week

	column weekday
		dataType: string
		summarizeBy: none
		sourceColumn: weekday
		sortByColumn: weekday_sort

	column weekday_sort = WEEKDAY ( dim_date[date], 2 )
		dataType: int64
		isHidden
		summarizeBy: none

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document ( File.Contents ( DataFolder & "dim_date.csv" ), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv] ),
				    Promoted = Table.PromoteHeaders ( Source, [PromoteAllScalars = true] ),
				    Typed = Table.TransformColumnTypes ( Promoted, {
				        {"date", type date}, {"year", Int64.Type}, {"month", type text},
				        {"iso_week", Int64.Type}, {"weekday", type text}
				    }, "en-US" )
				in
				    Typed
