table dim_item

	column item_id
		dataType: int64
		isKey
		summarizeBy: none
		sourceColumn: item_id

	column item
		dataType: string
		summarizeBy: none
		sourceColumn: item

	column weapon
		dataType: string
		summarizeBy: none
		sourceColumn: weapon

	column skin
		dataType: string
		summarizeBy: none
		sourceColumn: skin

	column wear
		dataType: string
		summarizeBy: none
		sourceColumn: wear
		sortByColumn: wear_ord

	column wear_ord
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: wear_ord

	column stattrak
		dataType: boolean
		summarizeBy: none
		sourceColumn: stattrak

	column souvenir
		dataType: boolean
		summarizeBy: none
		sourceColumn: souvenir

	column category
		dataType: string
		summarizeBy: none
		sourceColumn: category

	partition dim_item = m
		mode: import
		source =
				let
				    Source = Csv.Document ( File.Contents ( DataFolder & "dim_item.csv" ), [Delimiter = ",", Columns = 8, Encoding = 65001, QuoteStyle = QuoteStyle.Csv] ),
				    Promoted = Table.PromoteHeaders ( Source, [PromoteAllScalars = true] ),
				    Typed = Table.TransformColumnTypes ( Promoted, {
				        {"item_id", Int64.Type}, {"item", type text}, {"weapon", type text},
				        {"skin", type text}, {"wear", type text}, {"stattrak", type logical},
				        {"souvenir", type logical}, {"category", type text}
				    }, "en-US" ),
				    WithOrd = Table.AddColumn ( Typed, "wear_ord", each
				        let w = [wear] in
				        if w = "Factory New" then 1 else if w = "Minimal Wear" then 2 else if w = "Field-Tested" then 3
				        else if w = "Well-Worn" then 4 else if w = "Battle-Scarred" then 5 else 6, Int64.Type )
				in
				    WithOrd
